//
//  FriendsStyleKit.h
//  unWine
//
//  Created by Fabio Gomez on 6/14/17.
//  Copyright © 2017 LION Mobile LLC. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//

#import <UIKit/UIKit.h>



typedef enum : NSInteger
{
    FriendsStyleKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    FriendsStyleKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    FriendsStyleKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    FriendsStyleKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} FriendsStyleKitResizingBehavior;

extern CGRect FriendsStyleKitResizingBehaviorApply(FriendsStyleKitResizingBehavior behavior, CGRect rect, CGRect target);


@interface FriendsStyleKit : NSObject

// Colors
+ (UIColor*)fbBlue;

//// In Trial version of PaintCode, the code generation is limited to 3 canvases.

// Drawing Methods
+ (void)drawFacebook;
+ (void)drawFacebookWithFrame: (CGRect)targetFrame resizing: (FriendsStyleKitResizingBehavior)resizing;
+ (void)drawContactsCanvas;
+ (void)drawContactsCanvasWithFrame: (CGRect)targetFrame resizing: (FriendsStyleKitResizingBehavior)resizing;
+ (void)drawEmailCanvas;
+ (void)drawEmailCanvasWithFrame: (CGRect)targetFrame resizing: (FriendsStyleKitResizingBehavior)resizing;

@end
